# Generated by Django 5.0.6 on 2024-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_adminlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='UseName',
            new_name='UserName',
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='Password',
            field=models.CharField(max_length=150),
        ),
    ]
